name: release
on:
  push:
    branches:
      - release
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: gradle/gradle-build-action@v2
      - name: XCFramework を作る
        run: ./gradlew assembleXCFramework
      - name: ZIP ファイルを作る
        run: zip -r ga913kmp.xcframework.zip ga913kmp.xcframework/
        working-directory: ga913kmp/build/XCFrameworks/release/
      - name: バージョンを取得
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV
      - name: checksum を取得
        run: echo "checksum=$(swift package compute-checksum ga913kmp.xcframework.zip)" >> $GITHUB_ENV
        working-directory: ga913kmp/build/XCFrameworks/release/
#      - name: Package.swift を作る
#        run: 'npx ejs Package.swift.ejs -i '{"version": "${{ env.version }}", "checksum": "${{ env.checksum }}"}' -o Package.swift'
#      - name: コミットを積む
#        run: |
#          git config user.name "github-actions"
#          git config user.email "github-actions@github.com"
#          git add Package.swift
#          git commit -m "Package.swift を更新"
